### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by xanf-code** [Rexfordasamoah51/flutter_animated_splash_screen#1]
I see you have included all platform tags on pub.dev, does this support web as of now? if not are you planning to support web aswell?

**Comment by Rexfordasamoah51** [comment]
I am working on it, it will be ready ASAP 😉

**Comment by Rexfordasamoah51** [comment]
@xanf-code  I have publish a newer version which takes care of this. I make like to close this issue

Check the v1.3.0
