### ISSUE TITLE
Update Templates for AndroidManifest.xml

### ISSUE THREAD

**Issue by GeorgeW** [Rexfordasamoah51/flutter_animated_splash_screen#6]
android:name="${applicationName}"

per https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by Rexfordasamoah51** [comment]
I will work on that @GeorgeW

**Comment by Rexfordasamoah51** [comment]
@GeorgeW I have publish a newer version which takes care of this. I make like to close this issue 

Check the v1.3.0
